### ISSUE TITLE
VSCode -> Environment

### ISSUE THREAD

**Issue by MulverineX** [lolgeny/awesome-mcc#12]
DHP/Spyglass is a language server which means it has cross-environment compatibility, and there are lots of various utilities for other editors that can be listed

**Comment by lolgeny** [comment]
True for that though I'm not sure about stuff like NBT viewer. What other utilities are you thinking of?

**Comment by SPGoding** [comment]
DHP at its current stage is not non-VSCode friendly at all :facepalm:

**Comment by MulverineX** [comment]
Resolved by #14
